app:
  name: "Goi"
  mod: "dev"
  port: 8081
  version: "v0.0.2"
log:
  level: "debug"
  filename: "web.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: ""
  dbname: "web"
  max_open_connections: 200
  max_idle_connections: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
snowflake:
  start_time: "2022-05-03"
  machine_id: 1

